crud_product/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
]

products/urls.py
from django.urls import path

# views
from . import views


app_name='products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('create/', views.product_create, name='product_create'),
    path('update/<int:pk_product>/', views.product_update, name='product_update'),
    path('delete/<int:pk_product>/', views.product_delete, name='product_delete'),
]

products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField('Nome', max_length=100)
    price = models.FloatField('Preço')
    category = models.CharField('Categoria', max_length=100)

    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render, redirect

# models
from products.models import Product


def product_list(request):
    products = Product.objects.all()
    context = {
        'products':products,
    }
    return render(request, 'product_list.html', context)


def product_create(request):
    if request.method == 'POST':
        name = request.POST['name']
        price = request.POST['price']
        category = request.POST['category']

        Product.objects.create(
            name=name,
            price=price,
            category=category,
        )
        return redirect('products:product_list')
    return render(request, 'product_create.html')


def product_update(request, pk_product):
    product = Product.objects.get(pk=pk_product)
    context = {
        'product':product,
    }

    if request.method == 'POST':
        new_name = request.POST['name']
        new_price = request.POST['price']
        new_category = request.POST['category']

        product.name = new_name
        product.price = new_price
        product.category = new_category
        product.save()

        return redirect('products:product_list')

    return render(request, 'product_update.html', context)


def product_delete(request, pk_product):
    product = Product.objects.get(pk=pk_product)
    product.delete()
    return redirect('products:product_list')

products/templates/product_create.html
<div>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="name">Nome:</label>
            <input type="text" name="name" id="name">
        </div>
        <div>
            <label for="price">
                Preço:
            </label>
            <input type="number" name="price" id="price">
        </div>
        <div>
            <label for="category">
                Categoria:
            </label>
            <input type="text" name="category" id="category">
        </div>
        <div>
            <button type="submit">
                Salvar
            </button>
        </div>
    </form>
</div>

products/templates/product_list.html
<h1>Lista de Produtos</h1>

<div>
    <p>
        <a href="{% url 'products:product_create' %}">Adicionar Produto</a>
    </p>
    <table border="1">
        <thead>
        <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Preço</th>
            <th>Categoria</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.pk }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.category }}</td>
                    <td>
                        <a href="#">Ver</a> |
                        <a href="{% url 'products:product_update' product.pk %}">Editar</a> |
                        <a href="{% url 'products:product_delete' product.pk %}">Excluir</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

products/templates/product_update.html
<div>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="name">Nome:</label>
            <input type="text" name="name" id="name" value="{{ product.name }}">
        </div>
        <div>
            <label for="price">
                Preço:
            </label>
            <input type="number" name="price" id="price" value="{{ product.price }}">
        </div>
        <div>
            <label for="category">
                Categoria:
            </label>
            <input type="text" name="category" id="category" value="{{ product.category }}">
        </div>
        <div>
            <button type="submit">
                Salvar
            </button>
        </div>
    </form>
</div>